version: "3.9"

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8370:8443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d/me837.com.conf:/etc/nginx/conf.d/default.conf
    restart: always

networks:
  default:
    name: 837-network
    external: true

